language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - "12"

git:
  depth: 3

script:
  - yarn test

notifications:
  slack: $SLACK_NOTIFICATION_KEY
  email:
    recipients:
      - john.davis.2015.03@gmail.com
      - john.davis.2015@hotmail.com
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $HEROKU_API_KEY # desde heroku
  app: platzi-store-backend7
  on:
    repo: johnpablo7/platzi-store-backend
